Feat/auth
adebsa2401/BlogApp pull request #9
Opened 2023-03-09 12:41 UTC by adebsa2401

In this PR:

- we installed and set up `devise` gem
- we style `sign in` and `sign up` pages
Cheers

2023-03-09 23:03 UTC, MeqdamAlqudah requested changes
Hi @adebsa2401 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://user-images.githubusercontent.com/74744787/224179825-93b5ce58-9e51-4d4c-9863-d4d8ffba1e8b.png)

## Highlights
:+1: no linter errors 
:+1: design looks greate.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- it would be better to give more attention to the documentation while
reading it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 23:03 UTC, MeqdamAlqudah commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] Please the user should be able to confirm his info, it would be better to enable`:confirmable`.

2023-03-09 23:03 UTC, MeqdamAlqudah commented on app/controllers/application_controller.rb
> +  before_action :configure_sign_up_params, if: :devise_controller?
- [ ] Please as in devise documentation you should add this line to your application controller, as I can see currently the user can access any page without authentication, please fix this.
![image](https://user-images.githubusercontent.com/74744787/224178720-a2026605-08e3-4105-9161-62a2ede5b217.png)

2023-03-10 05:50 UTC, brytebee approved these changes
Hi, @adebsa2401 & @kennankole👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great implementing all suggested changes.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 05:50 UTC, brytebee commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable, :confirmable,
👏👏👏

2023-03-10 05:50 UTC, brytebee commented on app/controllers/application_controller.rb
> +  before_action :authenticate_user!
👏👏

2023-03-10 05:53 UTC, merged